version: "2"
services:
  app:
    container_name: robotics-api-docker
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - localhost
  localhost:
    container_name: localhost
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
